### PR TITLE
Forge 1.8.9

### LINKED ISSUE #131: Where ic can find minebot 1.8.9
https://github.com/michaelzangl/minebot/releases here only 1.8 releases :(
sorry for stupid question
Where i can find minebot 1.8.9*

### PR DESCRIPTION
**Pull request by SeasonalFerret**
I figured since this hasn't been updated in a year, I'd provide some download links to the final, built project. 
Fixes #131 #140 probably some others idk

https://transfer.sh/nPD0f/aimbow-1.0.jar
https://transfer.sh/R2AwZ/minebot-1.0.jar

Ignore the pull request to merge forge-1.8.9 to master. Although, I'd rather rename "master" to "1.8"

### CODE REVIEW

**Comment by deyvidaero** [comment]
@SylveonBottle file not found, can u re-upload please?

**Comment by SylveonBottle** [comment]
@deyvidaero https://drive.google.com/open?id=0B5v_6aY1qhicWXA3RENqb05UNnc

Only Minebot. Unfortunately the aimbow is v1.7, even though it's inside the 1.8 branch.

**Comment by michaelzangl** [comment]
I skipped 1.8.9 - closing this to focus on 1.15

**Comment by TheGamePRO112** [comment]
hey @SylveonBottle Do you still have the 1.8.9 version, the links no longer work?

**Comment by SeasonalFerret** [comment]
> hey @SylveonBottle Do you still have the 1.8.9 version, the links no longer work?

Lucky for you I found a copy on one of my old online drives.
[Minebot-1.0.jar.zip](https://github.com/michaelzangl/minebot/files/13553669/Minebot-1.0.jar.zip)

**Comment by TheGamePRO112** [comment]
Thank you so much you made my day

**Pull request closed without merging**
