### PR TITLE
1.9 Block updates

### PR DESCRIPTION
**Pull request by ghost**
next updates coming soon.....

### CODE REVIEW

**Comment by michaelzangl** [comment]
Oh, sorry. I was off (so many migration-branches).

Looks fine.

#167

**Comment by EpiXSim0n** [comment]
The Problem is i have no idea how to compile the files to the Minebot mod. I just added the missing Blocks to the file. Is there any tutorial how to compile java Projects? Sry for my bad english :P

**Comment by ghost** [comment]
So the next updates will follow in the next few days =)

**Comment by michaelzangl** [comment]
Nice, thanks. Why did you close this one?

**Comment by ghost** [comment]
@michaelzangl Cause I made a new one :P

_Sent from my Google Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Pull request closed without merging**
